import * as THREE from "three";
import{WebGPURenderer}from"three/webgpu";
import{loadGLTF}from"./gltf-loader.js";
import{applyMorphWeights,collectMorphBindings,type MorphBindingMap}from"./morphs.js";
import type{FaceWeights,Renderer,RendererScene,Transform,RuntimeAsset}from"@toon2.5d/core";
interface Scene extends RendererScene{readonly root:THREE.Group;readonly head:THREE.Mesh;readonly leftEye:THREE.Mesh;readonly rightEye:THREE.Mesh;readonly mouth:THREE.Mesh;morphBindings:MorphBindingMap;loadedRoot?:THREE.Object3D}
export interface WebGPUAvatarRendererOptions{readonly canvas:HTMLCanvasElement;readonly background?:number}
export class WebGPUAvatarRenderer implements Renderer{private readonly renderer:WebGPURenderer;private readonly scene=new THREE.Scene();private readonly camera=new THREE.OrthographicCamera(-1,1,1,-1,.01,100);private readonly scenes=new Map<string,Scene>();
 private constructor(renderer:WebGPURenderer){this.renderer=renderer;this.camera.position.z=5;this.scene.background=null}
 static async create(options:WebGPUAvatarRendererOptions):Promise<WebGPUAvatarRenderer>{const renderer=new WebGPURenderer({canvas:options.canvas,antialias:true});await renderer.init();if(options.background!==undefined)renderer.setClearColor(options.background,1);const instance=new WebGPUAvatarRenderer(renderer);return instance}
 createScene():RendererScene{const root=new THREE.Group();const head=new THREE.Mesh(new THREE.SphereGeometry(1,32,24),new THREE.MeshStandardMaterial({color:0xf0b28f,roughness:.8}));const material=new THREE.MeshStandardMaterial({color:0xffffff});const leftEye=new THREE.Mesh(new THREE.SphereGeometry(.22,20,16),material);const rightEye=leftEye.clone();const mouth=new THREE.Mesh(new THREE.SphereGeometry(.28,20,12),new THREE.MeshStandardMaterial({color:0x5b2530}));leftEye.position.set(-.34,.18,.86);rightEye.position.set(.34,.18,.86);mouth.position.set(0,-.28,.88);root.add(head,leftEye,rightEye,mouth);const fill=new THREE.HemisphereLight(0xffffff,0x555555,1.4);const key=new THREE.DirectionalLight(0xffffff,1.8);key.position.set(2,3,4);root.add(fill,key);this.scene.add(root);const scene={id:crypto.randomUUID(),root,head,leftEye,rightEye,mouth,morphBindings:new Map()};this.scenes.set(scene.id,scene);return scene}
 async loadAsset(scene:RendererScene,asset:RuntimeAsset):Promise<void>{const target=this.require(scene);const gltf=await loadGLTF(asset.uri);target.root.add(gltf.scene);target.loadedRoot=gltf.scene;target.head.visible=false;target.leftEye.visible=false;target.rightEye.visible=false;target.mouth.visible=false;target.morphBindings=collectMorphBindings(gltf.scene,asset.morphBindings)}
 setAvatarTransform(scene:RendererScene,transform:Transform):void{const target=this.require(scene);target.root.position.set(transform.position.x,transform.position.y,transform.position.z);target.root.scale.set(transform.scale.x,transform.scale.y,transform.scale.z);target.root.quaternion.set(transform.rotation.x,transform.rotation.y,transform.rotation.z,transform.rotation.w)}
 setFaceWeights(scene:RendererScene,weights:FaceWeights):void{const target=this.require(scene);if(target.morphBindings.size>0)applyMorphWeights(target.morphBindings,weights);target.root.rotation.y=(weights.eyeLookOutLeft-weights.eyeLookInLeft)*.2;target.root.rotation.x=(weights.eyeLookDownLeft-weights.eyeLookUpLeft)*.2}
 render(scene:RendererScene):void{this.require(scene);this.renderer.render(this.scene,this.camera)}
 resize(width:number,height:number):void{this.camera.left=-width/height;this.camera.right=width/height;this.camera.top=1;this.camera.bottom=-1;this.camera.updateProjectionMatrix();this.renderer.setSize(width,height,false)}
 dispose(scene:RendererScene):void{const target=this.require(scene);target.root.traverse(object=>{if(object instanceof THREE.Mesh){object.geometry.dispose();const materials=Array.isArray(object.material)?object.material:[object.material];for(const material of materials)material.dispose()}});this.scene.remove(target.root);this.scenes.delete(target.id)}
 destroy():void{for(const scene of [...this.scenes.values()])this.dispose(scene);this.renderer.dispose()}
 private require(scene:RendererScene):Scene{const target=this.scenes.get(scene.id);if(!target)throw new Error("Renderer scene is not owned by this WebGPU renderer.");return target}
}