import * as THREE from "three";
import{WebGPURenderer}from"three/webgpu";
import{loadGLTF}from"./gltf-loader.js";
import{createFallbackAvatar}from"./fallback.js";
import{applyMorphWeights,collectMorphBindings,type MorphBindingMap}from"./morphs.js";
import type{FaceWeights,Renderer,RendererScene,Transform,RuntimeAsset,PerspectiveCameraState,LookAtPose,CharacterCustomization,QualityTier}from"@toon2.5d/core";

interface Scene extends RendererScene{
 readonly root:THREE.Group;readonly scene:THREE.Scene;readonly head:THREE.Mesh;readonly leftEye:THREE.Mesh;readonly rightEye:THREE.Mesh;readonly mouth:THREE.Mesh;
 readonly camera:THREE.OrthographicCamera;readonly perspectiveCamera:THREE.PerspectiveCamera;
 morphBindings:MorphBindingMap;loadedRoot?:THREE.Object3D;readonly slots:Map<string,THREE.Group>;
 customizationMorphs:Partial<FaceWeights>;rig?:{headBone:string;leftEyeBone:string;rightEyeBone:string};mixer?:THREE.AnimationMixer;animations:THREE.AnimationClip[];
}
export interface WebGPUAvatarRendererOptions{readonly canvas:HTMLCanvasElement;readonly background?:number}

async function loadTextureSecure(uri:string,options:{readonly integrity?:string;readonly trustedOrigins?:readonly string[];readonly maxBytes?:number;readonly maxTexturePixels?:number}={}):Promise<THREE.Texture>{const parsed=new URL(uri);const dev=(globalThis as {process?:{env?:Record<string,string|undefined>}}).process?.env?.NODE_ENV==="development";const localhost=parsed.hostname==="localhost"||parsed.hostname==="127.0.0.1"||parsed.hostname==="::1";if(parsed.protocol!=="https:"&&!(dev&&parsed.protocol==="http:"&&localhost))throw new Error("Remote textures must use HTTPS.");if(options.trustedOrigins?.length&&!options.trustedOrigins.includes(parsed.origin))throw new Error("Texture origin is not trusted.");const response=await fetch(uri,{credentials:"omit"});if(!response.ok)throw new Error(`Texture request failed: ${response.status} ${response.statusText}`);const declared=response.headers.get("content-length");if(options.maxBytes!==undefined&&declared&&Number(declared)>options.maxBytes)throw new Error("Texture exceeds configured byte-size limit.");const data=await response.arrayBuffer();if(options.maxBytes!==undefined&&data.byteLength>options.maxBytes)throw new Error("Texture exceeds configured byte-size limit.");if(options.integrity){if(!options.integrity.startsWith("sha256-"))throw new Error("Only sha256 texture integrity is supported.");const digest=await crypto.subtle.digest("SHA-256",data);const encoded=btoa(String.fromCharCode(...new Uint8Array(digest)));if("sha256-"+encoded!==options.integrity)throw new Error("Texture integrity verification failed.");}const blob=new Blob([data]);const objectUrl=URL.createObjectURL(blob);try{const texture=await new THREE.TextureLoader().loadAsync(objectUrl);const image=texture.image as {width?:number;height?:number}|undefined;if(options.maxTexturePixels!==undefined&&image?.width&&image.height&&image.width*image.height>options.maxTexturePixels){texture.dispose();throw new Error("Texture pixel limit exceeded.");}return texture}finally{URL.revokeObjectURL(objectUrl)}}
function applyTextureToRoot(root:THREE.Object3D,texture:THREE.Texture):void{root.traverse(object=>{if(!(object instanceof THREE.Mesh))return;const materials=Array.isArray(object.material)?object.material:[object.material];for(const material of materials)if("map"in material){material.map=texture;material.needsUpdate=true}})}
function applyColorToRoot(root:THREE.Object3D,color:string):void{const parsed=new THREE.Color(color);root.traverse(object=>{if(!(object instanceof THREE.Mesh))return;const materials=Array.isArray(object.material)?object.material:[object.material];for(const material of materials)if("color"in material){(material as THREE.MeshStandardMaterial).color.copy(parsed);material.needsUpdate=true}})}
function disposeObject(root:THREE.Object3D):void{root.traverse(object=>{if(!(object instanceof THREE.Mesh))return;object.geometry.dispose();const materials=Array.isArray(object.material)?object.material:[object.material];for(const material of materials){for(const key of ["map","normalMap","roughnessMap","metalnessMap","emissiveMap","aoMap","alphaMap"]){const texture=material[key as keyof THREE.Material] as THREE.Texture|undefined;if(texture instanceof THREE.Texture)texture.dispose()}material.dispose()}})}
export class WebGPUAvatarRenderer implements Renderer{
 private readonly renderer:WebGPURenderer;private readonly scenes=new Map<string,Scene>();private quality:QualityTier="high";
 private constructor(renderer:WebGPURenderer){this.renderer=renderer}
 static async create(options:WebGPUAvatarRendererOptions):Promise<WebGPUAvatarRenderer>{const renderer=new WebGPURenderer({canvas:options.canvas,antialias:true});await renderer.init();if(options.background!==undefined)renderer.setClearColor(options.background,1);return new WebGPUAvatarRenderer(renderer)}
 createScene():RendererScene{
  const fallback=createFallbackAvatar();
  const {root,head,leftEye,rightEye,mouth}=fallback;
  const camera=new THREE.OrthographicCamera(-1,1,1,-1,.01,100);camera.position.z=5;
  const perspectiveCamera=new THREE.PerspectiveCamera(35,1,.01,100);perspectiveCamera.position.z=5;
  const threeScene=new THREE.Scene();threeScene.background=null;
  const fill=new THREE.HemisphereLight(0xffffff,0x555555,1.4);const key=new THREE.DirectionalLight(0xffffff,1.8);key.position.set(2,3,4);threeScene.add(fill,key,root);
  const slots=new Map<string,THREE.Group>();for(const slot of ["body","face","skin","hair","eyes","brows","nose","mouth","top","bottom","shoes","accessory"])slots.set(slot,new THREE.Group());slots.forEach(group=>root.add(group));
  const scene={id:crypto.randomUUID(),scene:threeScene,root,head,leftEye,rightEye,mouth,camera,perspectiveCamera,morphBindings:new Map(),slots,customizationMorphs:{},animations:[]};this.scenes.set(scene.id,scene);return scene
 }
 async loadAsset(scene:RendererScene,asset:RuntimeAsset):Promise<void>{const target=this.require(scene);const gltf=await loadGLTF(asset.uri,{...(asset.limits?.maxBytes!==undefined?{maxBytes:asset.limits.maxBytes}:{}),...(asset.limits?.maxTexturePixels!==undefined?{maxTexturePixels:asset.limits.maxTexturePixels}:{}),...(asset.limits?.maxVertices!==undefined?{maxVertices:asset.limits.maxVertices}:{}),...(asset.limits?.maxAnimations!==undefined?{maxAnimations:asset.limits.maxAnimations}:{}),...(asset.trustedOrigins?{trustedOrigins:asset.trustedOrigins}:{}),...(asset.integrity?{integrity:asset.integrity}:{})});if(this.scenes.get(scene.id)!==target){disposeObject(gltf.scene);throw new Error("Renderer scene was disposed during asset loading.")}if(target.loadedRoot){disposeObject(target.loadedRoot);target.loadedRoot.removeFromParent()}target.root.add(gltf.scene);target.loadedRoot=gltf.scene;target.head.visible=false;target.leftEye.visible=false;target.rightEye.visible=false;target.mouth.visible=false;target.morphBindings=collectMorphBindings(gltf.scene,asset.morphBindings);if(asset.rig)target.rig=asset.rig;else delete target.rig;target.mixer=new THREE.AnimationMixer(gltf.scene);target.animations=[...gltf.animations]}
 update(deltaSeconds:number):void{if(!Number.isFinite(deltaSeconds)||deltaSeconds<0)return;for(const target of this.scenes.values())target.mixer?.update(deltaSeconds)}
 getAnimationMixer(scene:RendererScene):THREE.AnimationMixer|undefined{return this.require(scene).mixer}
 getAnimationNames(scene:RendererScene):readonly string[]{return this.require(scene).animations.map(clip=>clip.name).filter(Boolean)}
 getBoneNames(scene:RendererScene):readonly string[]{const names:string[]=[];this.require(scene).loadedRoot?.traverse(object=>{if(object instanceof THREE.Bone)names.push(object.name)});return names}

 playAnimation(scene:RendererScene,name:string,options:{readonly loop?:THREE.AnimationActionLoopStyles;readonly repetitions?:number}={}):THREE.AnimationAction{const target=this.require(scene);if(!target.mixer)throw new Error("Scene has no native animation mixer.");const clip=THREE.AnimationClip.findByName(target.animations,name);if(!clip)throw new Error("Animation clip not found: "+name);const action=target.mixer.clipAction(clip);if(options.loop!==undefined)action.setLoop(options.loop,options.repetitions??Infinity);action.play();return action}
 setAvatarTransform(scene:RendererScene,transform:Transform):void{const target=this.require(scene);target.root.position.set(transform.position.x,transform.position.y,transform.position.z);target.root.scale.set(transform.scale.x,transform.scale.y,transform.scale.z);target.root.quaternion.set(transform.rotation.x,transform.rotation.y,transform.rotation.z,transform.rotation.w)}
 setFaceWeights(scene:RendererScene,weights:FaceWeights):void{const target=this.require(scene);const merged={...weights,...target.customizationMorphs};if(target.morphBindings.size>0)applyMorphWeights(target.morphBindings,merged);target.leftEye.scale.y=.15+.85*(1-merged.eyeBlinkLeft);target.rightEye.scale.y=.15+.85*(1-merged.eyeBlinkRight);target.mouth.scale.y=.2+.6*merged.jawOpen;target.mouth.scale.x=.8+.35*((merged.mouthSmileLeft+merged.mouthSmileRight)/2);target.mouth.position.y=-.28+.08*merged.jawOpen;target.root.rotation.y=(merged.eyeLookOutLeft-merged.eyeLookInLeft)*.2;target.root.rotation.x=(merged.eyeLookDownLeft-merged.eyeLookUpLeft)*.2}
 render(scene:RendererScene):void{const target=this.require(scene);const camera=target.root.userData.cameraMode==="perspective"?target.perspectiveCamera:target.camera;this.renderer.render(target.scene,camera)}
 setPerspectiveCamera(scene:RendererScene,camera:PerspectiveCameraState):void{const target=this.require(scene);target.perspectiveCamera.fov=camera.fov;target.perspectiveCamera.aspect=camera.aspect;target.perspectiveCamera.near=camera.near;target.perspectiveCamera.far=camera.far;target.perspectiveCamera.updateProjectionMatrix();target.root.userData.cameraMode="perspective"}
 setLookAtPose(scene:RendererScene,pose:LookAtPose):void{const target=this.require(scene);const mapping=target.rig;target.loadedRoot?.traverse(object=>{if(!mapping)return;if(object.name===mapping.headBone)object.quaternion.set(pose.head.x,pose.head.y,pose.head.z,pose.head.w);else if(object.name===mapping.leftEyeBone)object.quaternion.set(pose.leftEye.x,pose.leftEye.y,pose.leftEye.z,pose.leftEye.w);else if(object.name===mapping.rightEyeBone)object.quaternion.set(pose.rightEye.x,pose.rightEye.y,pose.rightEye.z,pose.rightEye.w)})}
 async applyCustomization(scene:RendererScene,customization:CharacterCustomization):Promise<void>{const target=this.require(scene);for(const item of customization.items){const slot=target.slots.get(item.slot);if(!slot)continue;if(item.slot==="accessory"){for(const child of slot.children.slice())if(child.userData.customizationItemId===item.id){slot.remove(child);disposeObject(child)}}else for(const child of slot.children.slice()){slot.remove(child);disposeObject(child)}if(item.morphs)target.customizationMorphs={...target.customizationMorphs,...item.morphs};if(item.assetUri){const gltf=await loadGLTF(item.assetUri,{...(item.limits?.maxBytes!==undefined?{maxBytes:item.limits.maxBytes}:{}),...(item.limits?.maxTexturePixels!==undefined?{maxTexturePixels:item.limits.maxTexturePixels}:{}),...(item.limits?.maxVertices!==undefined?{maxVertices:item.limits.maxVertices}:{}),...(item.limits?.maxAnimations!==undefined?{maxAnimations:item.limits.maxAnimations}:{}),...(item.trustedOrigins?{trustedOrigins:item.trustedOrigins}:{}),...(item.integrity?{integrity:item.integrity}:{})});if(this.scenes.get(scene.id)!==target){disposeObject(gltf.scene);throw new Error("Renderer scene was disposed during customization loading.")}gltf.scene.userData.customizationItemId=item.id;if(item.textureUri){const texture=await loadTextureSecure(item.textureUri,{integrity:item.textureIntegrity,trustedOrigins:item.textureTrustedOrigins,maxBytes:item.textureLimits?.maxBytes,maxTexturePixels:item.textureLimits?.maxTexturePixels});applyTextureToRoot(gltf.scene,texture)}slot.add(gltf.scene)}}if(customization.colors){for(const [slotName,color] of Object.entries(customization.colors)){if(!color)continue;const slot=target.slots.get(slotName);if(slot)applyColorToRoot(slot,color)}}}
 setQuality(tier:QualityTier):void{this.quality=tier;const ratios:Record<QualityTier,number>={low:.75,medium:1,high:1.5,ultra:2};this.renderer.setPixelRatio(ratios[tier])}
 resize(width:number,height:number):void{const aspect=Math.max(width,1)/Math.max(height,1);for(const target of this.scenes.values()){target.camera.left=-aspect;target.camera.right=aspect;target.camera.top=1;target.camera.bottom=-1;target.camera.updateProjectionMatrix();target.perspectiveCamera.aspect=aspect;target.perspectiveCamera.updateProjectionMatrix()}this.renderer.setSize(width,height,false)}
 dispose(scene:RendererScene):void{const target=this.require(scene);disposeObject(target.root);target.scene.remove(target.root);this.scenes.delete(target.id)}
 destroy():void{for(const target of [...this.scenes.values()])this.dispose(target);this.renderer.dispose()}
 private require(scene:RendererScene):Scene{const target=this.scenes.get(scene.id);if(!target)throw new Error("Renderer scene is not owned by this WebGPU renderer.");return target}
}
