import {sample} from "./interpolate.js";
import type {Clip} from "./types.js";
import type {ExpressionContribution,ExpressionSource} from "@toon2.5d/core";

export type StateTrigger=string;
export type TransitionCondition=(context:Readonly<StateMachineContext>)=>boolean;
export interface StateMachineContext{readonly deltaSeconds:number;readonly elapsedSeconds:number;readonly stateElapsedSeconds:number;readonly parameters:Readonly<Record<string,number>>;readonly triggers:ReadonlySet<string>}
export interface AnimationStateDefinition{readonly id:string;readonly clip:string;readonly loop?:boolean;readonly speed?:number;readonly onEnter?:(context:StateMachineContext)=>void;readonly onExit?:(context:StateMachineContext)=>void}
export interface AnimationTransition{readonly from:string;readonly to:string;readonly duration:number;readonly trigger?:StateTrigger;readonly conditions?:readonly TransitionCondition[];readonly onTransition?:(from:string,to:string)=>void}
export interface AnimationStateMachineDefinition{readonly initial:string;readonly states:readonly AnimationStateDefinition[];readonly transitions:readonly AnimationTransition[]}
export interface AnimationStateMachine{readonly currentState:string;readonly previousState:string|null;readonly transitionProgress:number;readonly isTransitioning:boolean;setParameter(name:string,value:number):void;setTrigger(trigger:string):void;clearTrigger(trigger:string):void;reset():void;update(deltaSeconds:number):void;consumeOutput():Readonly<{clips:readonly Clip[];weights:readonly number[];times:readonly number[];loops:readonly boolean[]}>}
function finite(value:number,name:string):void{if(!Number.isFinite(value)||value<0)throw new RangeError(name+" must be finite and non-negative.")}
function validate(def:AnimationStateMachineDefinition):void{const ids=new Set<string>();for(const state of def.states){if(!state.id||ids.has(state.id))throw new RangeError("Animation state ids must be unique.");ids.add(state.id);if(state.speed!==undefined&&(!Number.isFinite(state.speed)||state.speed<0))throw new RangeError("Animation state speed must be finite and non-negative.");}if(!ids.has(def.initial))throw new RangeError("Initial animation state does not exist.");for(const transition of def.transitions){finite(transition.duration,"Transition duration");if(!ids.has(transition.from)||!ids.has(transition.to))throw new RangeError("Transition references a missing state.");}}
export function createAnimationStateMachine(definition:AnimationStateMachineDefinition,clips:readonly Clip[]):AnimationStateMachine{
 validate(definition);const states=new Map(definition.states.map(state=>[state.id,state]));const clipMap=new Map(clips.map(clip=>[clip.id,clip]));for(const state of definition.states)if(!clipMap.has(state.clip))throw new RangeError("Animation state references a missing clip.");
 let current=definition.initial,previous:string|null=null,stateElapsed=0,transitionElapsed=0,fromStateElapsed=0,elapsed=0;let transition:AnimationTransition|null=null;let parameters:Record<string,number>={};const triggers=new Set<string>();const output={clips:[] as Clip[],weights:[] as number[],times:[] as number[],loops:[] as boolean[]};
 const context=(deltaSeconds:number):StateMachineContext=>({deltaSeconds,elapsedSeconds:elapsed,stateElapsedSeconds:stateElapsed,parameters,triggers});
 const enter=(delta:number)=>states.get(current)?.onEnter?.(context(delta));
 enter(0);
 return{get currentState(){return current},get previousState(){return previous},get transitionProgress(){return transition?Math.min(1,transitionElapsed/Math.max(transition.duration,Number.EPSILON)):1},get isTransitioning(){return transition!==null},
 setParameter(name,value){if(!name||!Number.isFinite(value))throw new RangeError("Animation parameter must have a non-empty name and finite value.");parameters={...parameters,[name]:value};},
 setTrigger(trigger){if(!trigger)throw new RangeError("Animation trigger must not be empty.");triggers.add(trigger);},clearTrigger(trigger){triggers.delete(trigger);},
 reset(){current=definition.initial;previous=null;stateElapsed=0;transitionElapsed=0;fromStateElapsed=0;elapsed=0;transition=null;triggers.clear();parameters={};enter(0);},
 update(delta){finite(delta,"Animation state machine delta");elapsed+=delta;if(transition){transitionElapsed+=delta;if(transitionElapsed>=transition.duration){transition=null;transitionElapsed=0;previous=null;}}stateElapsed+=delta;if(!transition){const next=definition.transitions.find(item=>item.from===current&&(!item.trigger||triggers.has(item.trigger))&&(!item.conditions||item.conditions.every(condition=>condition(context(delta)))));if(next){const from=current;states.get(from)?.onExit?.(context(delta));previous=from;fromStateElapsed=stateElapsed;current=next.to;stateElapsed=0;transition=next;transitionElapsed=0;next.onTransition?.(from,current);enter(delta);}}triggers.clear();},
 consumeOutput(){output.clips.length=0;output.weights.length=0;output.times.length=0;output.loops.length=0;const state=states.get(current);if(!state)throw new RangeError("Current animation state does not exist.");const clip=clipMap.get(state.clip);if(!clip)throw new RangeError("Current animation clip does not exist.");if(transition&&previous){const from=states.get(previous);if(!from)throw new RangeError("Previous animation state does not exist.");const fromClip=clipMap.get(from.clip);if(!fromClip)throw new RangeError("Previous animation clip does not exist.");const progress=Math.min(1,transitionElapsed/Math.max(transition.duration,Number.EPSILON));output.clips.push(fromClip,clip);output.weights.push(1-progress,progress);output.times.push(fromStateElapsed*(from.speed??1),stateElapsed*(state.speed??1));output.loops.push(from.loop!==false,state.loop!==false);}else{output.clips.push(clip);output.weights.push(1);output.times.push(stateElapsed*(state.speed??1));output.loops.push(state.loop!==false);}return output;}}
}
export function stateMachineSource(machine:AnimationStateMachine):ExpressionSource{const contributions:ExpressionContribution[]=[];return{id:"state-machine",evaluate(context){machine.update(context.deltaSeconds);const output=machine.consumeOutput();contributions.length=0;for(let index=0;index<output.clips.length;index+=1){const clip=output.clips[index];const weight=output.weights[index]??0;const time=output.times[index]??0;if(!clip)continue;for(const track of clip.tracks){const value=sample(track.keys,clip.duration>0?time%clip.duration:0,track.easing);if(value>0)contributions.push({source:"state-machine",parameter:track.parameter,value,weight,priority:30,mode:"add"});}}return contributions}}}
