import type {Clip} from "./types.js";

export type StateTrigger=string;
export type TransitionCondition=(context:Readonly<StateMachineContext>)=>boolean;
export interface StateMachineContext{readonly deltaSeconds:number;readonly elapsedSeconds:number;readonly stateElapsedSeconds:number;readonly parameters:Readonly<Record<string,number>>;readonly triggers:ReadonlySet<string>}
export interface AnimationStateDefinition{readonly id:string;readonly clip:string;readonly loop?:boolean;readonly speed?:number;readonly onEnter?:(context:StateMachineContext)=>void;readonly onExit?:(context:StateMachineContext)=>void}
export interface AnimationTransition{readonly from:string;readonly to:string;readonly duration:number;readonly trigger?:StateTrigger;readonly conditions?:readonly TransitionCondition[];readonly onTransition?:(from:string,to:string)=>void}
export interface AnimationStateMachineDefinition{readonly initial:string;readonly states:readonly AnimationStateDefinition[];readonly transitions:readonly AnimationTransition[];readonly clips:readonly Clip[]}
export interface AnimationStateMachine{readonly currentState:string;readonly previousState:string|null;readonly transitionProgress:number;readonly isTransitioning:boolean;setParameter(name:string,value:number):void;setTrigger(trigger:string):void;clearTrigger(trigger:string):void;reset():void;update(deltaSeconds:number):void;consumeOutput():Readonly<{clips:readonly Clip[];weights:readonly number[];times:readonly number[];loops:readonly boolean[]}>}
function finite(value:number,name:string):void{if(!Number.isFinite(value)||value<0)throw new RangeError(name+" must be finite and non-negative.");}
function validate(def:AnimationStateMachineDefinition):void{const ids=new Set<string>();for(const state of def.states){if(!state.id||ids.has(state.id))throw new RangeError("Animation state ids must be unique.");ids.add(state.id);if(state.speed!==undefined&&(!Number.isFinite(state.speed)||state.speed<0))throw new RangeError("Animation state speed must be finite and non-negative.");}if(!ids.has(def.initial))throw new RangeError("Initial animation state does not exist.");const clips=new Set(def.clips.map(clip=>clip.id));for(const state of def.states)if(!clips.has(state.clip))throw new RangeError("Animation state references a missing clip.");for(const item of def.transitions){finite(item.duration,"Transition duration");if(!ids.has(item.from)||!ids.has(item.to))throw new RangeError("Transition references a missing state.");}}
export function createAnimationStateMachine(definition:AnimationStateMachineDefinition):AnimationStateMachine{
 validate(definition);const states=new Map(definition.states.map(state=>[state.id,state]));const clips=new Map(definition.clips.map(clip=>[clip.id,clip]));let current=definition.initial;let previous:string|null=null;let stateElapsed=0;let transitionElapsed=0;let transition:AnimationTransition|null=null;let parameters:Record<string,number>={};const triggers=new Set<string>();const output={clips:[] as Clip[],weights:[] as number[],times:[] as number[],loops:[] as boolean[]};
 const enter=()=>states.get(current)?.onEnter?.({deltaSeconds:0,elapsedSeconds:0,stateElapsedSeconds:stateElapsed,parameters,triggers});enter();
 const choose=()=>definition.transitions.find(item=>item.from===current&&(!item.trigger||triggers.has(item.trigger))&&(!item.conditions||item.conditions.every(condition=>condition({deltaSeconds:0,elapsedSeconds:0,stateElapsedSeconds:stateElapsed,parameters,triggers}))))??null;
 return{get currentState(){return current},get previousState(){return previous},get transitionProgress(){return transition?Math.min(1,transitionElapsed/Math.max(transition.duration,Number.EPSILON)):1},get isTransitioning(){return transition!==null},
  setParameter(name,value){if(!name||!Number.isFinite(value))throw new RangeError("Animation parameter must have a non-empty name and finite value.");parameters={...parameters,[name]:value};},setTrigger(trigger){if(!trigger)throw new RangeError("Animation trigger must not be empty.");triggers.add(trigger);},clearTrigger(trigger){triggers.delete(trigger);},
  reset(){current=definition.initial;previous=null;stateElapsed=0;transitionElapsed=0;transition=null;triggers.clear();parameters={};enter();},
  update(delta){finite(delta,"Animation state machine delta");stateElapsed+=delta;const context={deltaSeconds:delta,elapsedSeconds:0,stateElapsedSeconds:stateElapsed,parameters,triggers};if(!transition){const next=choose();if(next){states.get(current)?.onExit?.(context);previous=current;current=next.to;stateElapsed=0;transition=next;transitionElapsed=0;next.onTransition?.(previous,current);states.get(current)?.onEnter?.(context);}}if(transition){transitionElapsed+=delta;if(transitionElapsed>=transition.duration){transition=null;transitionElapsed=0;previous=null;}}triggers.clear();},
  consumeOutput(){output.clips.length=0;output.weights.length=0;output.times.length=0;output.loops.length=0;const state=states.get(current)!;const clip=clips.get(state.clip)!;if(transition&&previous){const from=states.get(previous)!;const fromClip=clips.get(from.clip)!;const progress=Math.min(1,transitionElapsed/Math.max(transition.duration,Number.EPSILON));output.clips.push(fromClip,clip);output.weights.push(1-progress,progress);output.times.push(stateElapsed, stateElapsed);output.loops.push(from.loop!==false,state.loop!==false);}else{output.clips.push(clip);output.weights.push(1);output.times.push(stateElapsed*(state.speed??1));output.loops.push(state.loop!==false);}return output;}};
}